name: 'Project Build and Deploy'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - infra/tf/**
      - '.github/workflows/infra_**'
    branches:
      - master

env:
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

permissions:
  id-token: write

jobs:
  build-deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install PNPM
        run: |
          npm install -g pnpm@9.15.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: GitHub-Session
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd infra/tf
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.AWS_BUCKET_KEY_NAME }}" \
            -backend-config="region=${{ secrets.REGION }}"

      - name: Terraform Validate
        id: validate
        run: |
          cd infra/tf
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd infra/tf
          terraform plan -no-color \
            -var "aws_bucket_name=${{ secrets.AWS_BUCKET_NAME }}" \
            -var "aws_bucket_key=${{ secrets.AWS_BUCKET_KEY_NAME }}" \
            -var "region=${{ secrets.REGION }}"

      - name: Terraform Apply
        run: |
          cd infra/tf
          terraform apply -auto-approve
